/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.BorrowReturnDAO;
import dao.ExportFile;
import dao.ImportBookDAO;
import dao.ImportDAO;
import dao.ViolationDAO;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BorrowReturn;
import model.ErrorBook;
import model.Import;
import model.ImportBook;
import model.User;
import model.Violation;
/**
 *
 * @author Admin
 */
public class ReportViolationFrm extends javax.swing.JFrame {

    /**
     * Creates new form ReportViolationFrm
     */
    private User user;
    DefaultTableModel modelViolation;
    private List<Violation> listviolation;
    public ReportViolationFrm(User user) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = user;
        modelViolation = (DefaultTableModel) tableViolation.getModel();
        try {
            listviolation = new ViolationDAO().getAllViolation();
            showTableViolation();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi khi lấy dữ liệu!");
            Logger.getLogger(ReportFrm1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableViolation = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        buttonViolationFilter = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        dateViolationStart = new com.toedter.calendar.JDateChooser();
        dateViolationEnd = new com.toedter.calendar.JDateChooser();
        labelQuantityBookViolation = new javax.swing.JLabel();
        labelAmountViolation = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        textSearchViolation = new javax.swing.JTextField();
        buttonSearchViolation = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        buttonExportViolation = new javax.swing.JButton();
        buttonResetViolation = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        labelQuantityViolation = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        buttonView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));

        tableViolation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Người vi phạm", "Nội dung", "Số lượng sách", "Ngày", "Tiền phạt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableViolation);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel23.setText("Từ");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel24.setText("đến ");

        buttonViolationFilter.setText("Lọc");
        buttonViolationFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViolationFilterActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel25.setText("Tổng số lượng sách:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel26.setText("Tổng đền bù:");

        labelQuantityBookViolation.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelQuantityBookViolation.setText("0");

        labelAmountViolation.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelAmountViolation.setText("0");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel31.setText("Người vi phạm:");

        buttonSearchViolation.setText("Tìm kiếm");
        buttonSearchViolation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchViolationActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel32.setText("Danh sách biên bản vi phạm");

        buttonExportViolation.setText("Xuất");
        buttonExportViolation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExportViolationActionPerformed(evt);
            }
        });

        buttonResetViolation.setText("Về ban đầu");
        buttonResetViolation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetViolationActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel28.setText("Tổng số biên bản: ");

        labelQuantityViolation.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        labelQuantityViolation.setText("0");

        buttonExit.setText("Thoát");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonView.setText("Xem chi tiết");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel32)
                .addContainerGap(359, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(textSearchViolation, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonSearchViolation))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateViolationStart, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateViolationEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonViolationFilter)))
                        .addGap(214, 214, 214))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelQuantityViolation, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelQuantityBookViolation, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonView)
                        .addGap(44, 44, 44)
                        .addComponent(buttonResetViolation)
                        .addGap(62, 62, 62)
                        .addComponent(buttonExportViolation)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelAmountViolation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonExit)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addComponent(dateViolationStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateViolationEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(buttonViolationFilter)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(textSearchViolation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearchViolation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(labelQuantityBookViolation)
                    .addComponent(jLabel26)
                    .addComponent(labelAmountViolation)
                    .addComponent(jLabel28)
                    .addComponent(labelQuantityViolation))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExportViolation)
                    .addComponent(buttonResetViolation)
                    .addComponent(buttonExit)
                    .addComponent(buttonView))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 955, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        ReportFrm frm = new ReportFrm(user);
        this.setVisible(false);
        frm.setVisible(true);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonViolationFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViolationFilterActionPerformed
        // TODO add your handling code here:
        textSearchViolation.setText("");
        Date dateStartUtil = dateViolationStart.getDate();
        Date dateEndUtil = dateViolationEnd.getDate();
        try {
            listviolation = new ViolationDAO().getViolationByDate(new java.sql.Date(dateStartUtil.getTime()), new java.sql.Date(dateEndUtil.getTime()));
            showTableViolation();
        } catch (SQLException ex) {
            Logger.getLogger(ReportViolationFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonViolationFilterActionPerformed

    private void buttonSearchViolationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchViolationActionPerformed
        // TODO add your handling code here:
        dateViolationStart.setDate(null);
        dateViolationEnd.setDate(null);
        String keyString = textSearchViolation.getText();
        if(keyString.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập từ khóa!"); 
        }
        else{
            try {
                listviolation = new ViolationDAO().getViolationByKey(keyString);
                showTableViolation();
            } catch (SQLException ex) {
                Logger.getLogger(ReportViolationFrm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_buttonSearchViolationActionPerformed

    private void buttonResetViolationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetViolationActionPerformed
        // TODO add your handling code here:
        try {
            dateViolationStart.setDate(null);
            dateViolationEnd.setDate(null);
            textSearchViolation.setText("");
            listviolation = new ViolationDAO().getAllViolation();
            showTableViolation();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi khi lấy dữ liệu!");
            Logger.getLogger(ReportFrm1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonResetViolationActionPerformed

    private void buttonExportViolationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExportViolationActionPerformed
        try {
            // TODO add your handling code here:
            new ExportFile().exportReportViolation(listviolation);
            JOptionPane.showMessageDialog(rootPane, "Đã xuất file thành công!");
        } catch (IOException ex) {
            Logger.getLogger(ReportViolationFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonExportViolationActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        // TODO add your handling code here:
        int selectIndex = tableViolation.getSelectedRow();
        if(selectIndex == -1){
            JOptionPane.showMessageDialog(rootPane, "Hãy chọn một hàng trong bảng!");
        }
        else {
            Violation v = listviolation.get(selectIndex);
            ViolationFrm frm = new ViolationFrm(this, rootPaneCheckingEnabled);
            frm.showViolation(v);
            frm.setVisible(true);
        }
    }//GEN-LAST:event_buttonViewActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReportViolationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReportViolationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReportViolationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReportViolationFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReportViolationFrm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonExportViolation;
    private javax.swing.JButton buttonResetViolation;
    private javax.swing.JButton buttonSearchViolation;
    private javax.swing.JButton buttonView;
    private javax.swing.JButton buttonViolationFilter;
    private com.toedter.calendar.JDateChooser dateViolationEnd;
    private com.toedter.calendar.JDateChooser dateViolationStart;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelAmountViolation;
    private javax.swing.JLabel labelQuantityBookViolation;
    private javax.swing.JLabel labelQuantityViolation;
    private javax.swing.JTable tableViolation;
    private javax.swing.JTextField textSearchViolation;
    // End of variables declaration//GEN-END:variables

    private void showTableViolation() {
        labelQuantityViolation.setText(String.valueOf(listviolation.size()));
        modelViolation.setRowCount(0);
        int index = 1;
        int quantityBook = 0;
        int amount = 0;
        for(Violation v : listviolation){
            
            int price = 0;
            for(BorrowReturn br : v.getBorrowReturn()){
                for(ErrorBook eb : br.getErrorBook()){
                    price = eb.getPercentage() * br.getAbook().getBook().getPrice() / 100;
                    amount += price;
                }
            }
            
            quantityBook += v.getBorrowReturn().size();
            modelViolation.addRow(new Object[]{
                index++, v.getReader().getFullname(), v.getNote(), v.getBorrowReturn().size(), v.getDate(), price
            });
        }
        
        labelQuantityBookViolation.setText(String.valueOf(quantityBook));
        labelAmountViolation.setText(String.valueOf(amount) + " VND");
    }
}
